ci:
  autofix_commit_msg: "style: auto fixes from pre-commit.ci"
  autoupdate_commit_msg: "chore: pre-commit autoupdate"

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
        exclude: '\.(d\.ts|vsix|svg|png|ico|wasm)$'
      - id: end-of-file-fixer
        exclude: '\.(d\.ts|vsix|svg|png|ico|wasm)$'
      - id: check-yaml
      - id: check-added-large-files
        args: ["--maxkb=10000"]
