/**
 * ------------------------------------------------------------------
 * LSP Server Registry
 * ------------------------------------------------------------------
 * Danh sách LSP servers có sẵn để cài đặt
 * ------------------------------------------------------------------
 */

export interface LSPServer {
  id: string;
  name: string;
  language: string;
  npmPackage: string;
  description: string;
  homepage?: string;
  icon?: string;
  installed?: boolean;
}

// CDN Icon Base
const CDN = 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons';

function icon(name: string): string {
  return `${CDN}/${name}/${name}-original.svg`;
}

function iconPlain(name: string): string {
  return `${CDN}/${name}/${name}-plain.svg`;
}

export const AVAILABLE_LSP_SERVERS: LSPServer[] = [
  // ═══════════════════════════════════════════════════════════════════════
  // WEB FRONTEND
  // ═══════════════════════════════════════════════════════════════════════
  {
    id: 'typescript',
    name: 'TypeScript Language Server',
    language: 'TypeScript / JavaScript',
    npmPackage: 'typescript-language-server',
    description: 'IntelliSense, auto-complete, diagnostics for .ts / .tsx / .js / .jsx files',
    homepage: 'https://github.com/typescript-language-server/typescript-language-server',
    icon: icon('typescript'),
  },
  {
    id: 'html',
    name: 'HTML Language Server',
    language: 'HTML',
    npmPackage: 'vscode-langservers-extracted',
    description: 'Auto-complete, validation, and emmet for HTML',
    homepage: 'https://github.com/hrsh7th/vscode-langservers-extracted',
    icon: icon('html5'),
  },
  {
    id: 'css',
    name: 'CSS Language Server',
    language: 'CSS / SCSS / Less',
    npmPackage: 'vscode-langservers-extracted',
    description: 'Auto-complete, linting, and validation for stylesheets',
    homepage: 'https://github.com/hrsh7th/vscode-langservers-extracted',
    icon: icon('css3'),
  },
  {
    id: 'tailwindcss',
    name: 'Tailwind CSS IntelliSense',
    language: 'Tailwind CSS',
    npmPackage: '@tailwindcss/language-server',
    description: 'IntelliSense for Tailwind CSS classes',
    homepage: 'https://github.com/tailwindlabs/tailwindcss-intellisense',
    icon: iconPlain('tailwindcss'),
  },
  {
    id: 'vue',
    name: 'Vue Language Server (Volar)',
    language: 'Vue.js',
    npmPackage: '@vue/language-server',
    description: 'Official Vue.js language support with TypeScript integration',
    homepage: 'https://github.com/vuejs/language-tools',
    icon: icon('vuejs'),
  },
  {
    id: 'svelte',
    name: 'Svelte Language Server',
    language: 'Svelte',
    npmPackage: 'svelte-language-server',
    description: 'Language support for Svelte framework',
    homepage: 'https://github.com/sveltejs/language-tools',
    icon: icon('svelte'),
  },
  {
    id: 'angular',
    name: 'Angular Language Service',
    language: 'Angular',
    npmPackage: '@angular/language-service',
    description: 'IntelliSense for Angular templates and components',
    homepage: 'https://angular.io/guide/language-service',
    icon: icon('angularjs'),
  },
  {
    id: 'astro',
    name: 'Astro Language Server',
    language: 'Astro',
    npmPackage: '@astrojs/language-server',
    description: 'Language support for Astro framework',
    homepage: 'https://github.com/withastro/language-tools',
    icon: icon('astro'),
  },
  {
    id: 'react',
    name: 'TypeScript Language Server',
    language: 'React / JSX',
    npmPackage: 'typescript-language-server',
    description: 'IntelliSense for React/JSX via TypeScript server',
    homepage: 'https://github.com/typescript-language-server/typescript-language-server',
    icon: icon('react'),
  },
  {
    id: 'qwik',
    name: 'Qwik Language Server',
    language: 'Qwik',
    npmPackage: 'qwik-language-server',
    description: 'Language support for Qwik framework',
    homepage: 'https://github.com/QwikDev/qwik',
    icon: icon('qwik'),
  },
  {
    id: 'solidjs',
    name: 'TypeScript Language Server',
    language: 'SolidJS',
    npmPackage: 'typescript-language-server',
    description: 'IntelliSense for SolidJS via TypeScript server',
    homepage: 'https://github.com/typescript-language-server/typescript-language-server',
    icon: icon('solidjs'),
  },
  {
    id: 'preact',
    name: 'TypeScript Language Server',
    language: 'Preact',
    npmPackage: 'typescript-language-server',
    description: 'IntelliSense for Preact via TypeScript server',
    homepage: 'https://github.com/typescript-language-server/typescript-language-server',
    icon: icon('preact'),
  },
  {
    id: 'lit',
    name: 'Lit Language Server',
    language: 'Lit / Web Components',
    npmPackage: 'lit-analyzer',
    description: 'IntelliSense for Lit elements and templates',
    homepage: 'https://github.com/runem/lit-analyzer',
    icon: icon('lit'),
  },
  {
    id: 'stencil',
    name: 'Stencil Language Server',
    language: 'Stencil.js',
    npmPackage: '@stencil/language-server',
    description: 'Language support for Stencil web components',
    homepage: 'https://stenciljs.com/',
    icon: icon('stencil'),
  },
  {
    id: 'mdx',
    name: 'MDX Language Server',
    language: 'MDX',
    npmPackage: 'mdx-language-server',
    description: 'IntelliSense for MDX (Markdown + JSX) files',
    homepage: 'https://github.com/mdx-js/mdx-analyzer',
    icon: icon('markdown'),
  },
  {
    id: 'emmet',
    name: 'Emmet Language Server',
    language: 'Emmet Abbreviations',
    npmPackage: '@olrtg/emmet-language-server',
    description: 'Emmet abbreviation expansion in any editor',
    homepage: 'https://github.com/olrtg/emmet-language-server',
    icon: icon('html5'), // no emmet icon, use html5
  },

  // ═══════════════════════════════════════════════════════════════════════
  // LINTING & FORMATTING
  // ═══════════════════════════════════════════════════════════════════════
  {
    id: 'eslint',
    name: 'ESLint Language Server',
    language: 'JavaScript / TypeScript',
    npmPackage: 'vscode-eslint-language-server',
    description: 'Linting and auto-fix for JavaScript/TypeScript via ESLint',
    homepage: 'https://github.com/microsoft/vscode-eslint',
    icon: icon('eslint'),
  },
  {
    id: 'prettier',
    name: 'Prettier Language Server',
    language: 'Multi-language',
    npmPackage: 'prettier-language-server',
    description: 'Opinionated code formatter for JS/TS/CSS/HTML/JSON and more',
    homepage: 'https://github.com/prettier/prettier',
    icon: icon('prettier'),
  },
  {
    id: 'stylelint',
    name: 'Stylelint Language Server',
    language: 'CSS / SCSS',
    npmPackage: 'stylelint-lsp',
    description: 'Linting for CSS, SCSS, and styled-components',
    homepage: 'https://github.com/stylelint/stylelint',
    icon: icon('stylelint'),
  },
  {
    id: 'biome',
    name: 'Biome',
    language: 'JavaScript / TypeScript / JSON / CSS',
    npmPackage: '@biomejs/biome',
    description: 'Fast linter and formatter (ESLint + Prettier replacement)',
    homepage: 'https://github.com/biomejs/biome',
    icon: icon('biome'),
  },

  // ═══════════════════════════════════════════════════════════════════════
  // BACKEND LANGUAGES
  // ═══════════════════════════════════════════════════════════════════════
  {
    id: 'python',
    name: 'Pyright',
    language: 'Python',
    npmPackage: 'pyright',
    description: 'Fast type checker and language server for Python',
    homepage: 'https://github.com/microsoft/pyright',
    icon: icon('python'),
  },
  {
    id: 'pylsp',
    name: 'Python LSP Server',
    language: 'Python',
    npmPackage: 'python-lsp-server',
    description: 'Alternative Python language server with plugin support',
    homepage: 'https://github.com/python-lsp/python-lsp-server',
    icon: icon('python'),
  },
  {
    id: 'rust',
    name: 'Rust Analyzer',
    language: 'Rust',
    npmPackage: 'rust-analyzer',
    description: 'First-class Rust language support with cargo integration',
    homepage: 'https://rust-analyzer.github.io/',
    icon: iconPlain('rust'),
  },
  {
    id: 'go',
    name: 'Gopls',
    language: 'Go',
    npmPackage: 'gopls',
    description: 'Official Go language server from the Go team',
    homepage: 'https://github.com/golang/tools/tree/master/gopls',
    icon: icon('go'),
  },
  {
    id: 'java',
    name: 'Eclipse JDT LS',
    language: 'Java',
    npmPackage: 'java-debug',
    description: 'Full Java support with Gradle/Maven integration',
    homepage: 'https://github.com/eclipse-jdtls/eclipse.jdt.ls',
    icon: icon('java'),
  },
  {
    id: 'kotlin',
    name: 'Kotlin Language Server',
    language: 'Kotlin',
    npmPackage: 'kotlin-language-server',
    description: 'Language server for Kotlin programming',
    homepage: 'https://github.com/fwcd/kotlin-language-server',
    icon: icon('kotlin'),
  },
  {
    id: 'scala',
    name: 'Metals',
    language: 'Scala',
    npmPackage: 'metals-languageserver',
    description: 'Scala language server with build server support',
    homepage: 'https://scalameta.org/metals/',
    icon: icon('scala'),
  },
  {
    id: 'csharp',
    name: 'OmniSharp',
    language: 'C#',
    npmPackage: 'omnisharp-roslyn',
    description: 'C# language services for .NET projects',
    homepage: 'https://github.com/OmniSharp/omnisharp-roslyn',
    icon: icon('csharp'),
  },
  {
    id: 'fsharp',
    name: 'FsAutoComplete',
    language: 'F#',
    npmPackage: 'fsautocomplete',
    description: 'Language server for F# with .NET integration',
    homepage: 'https://github.com/fsharp/FsAutoComplete',
    icon: icon('fsharp'),
  },
  {
    id: 'php',
    name: 'Intelephense',
    language: 'PHP',
    npmPackage: 'intelephense',
    description: 'High performance PHP language server',
    homepage: 'https://intelephense.com/',
    icon: icon('php'),
  },
  {
    id: 'ruby',
    name: 'Ruby LSP',
    language: 'Ruby',
    npmPackage: 'ruby-lsp',
    description: 'Official Ruby language server from Shopify',
    homepage: 'https://github.com/Shopify/ruby-lsp',
    icon: icon('ruby'),
  },
  {
    id: 'elixir',
    name: 'ElixirLS',
    language: 'Elixir',
    npmPackage: 'elixir-ls',
    description: 'Language server for Elixir and Erlang',
    homepage: 'https://github.com/elixir-lsp/elixir-ls',
    icon: icon('elixir'),
  },
  {
    id: 'erlang',
    name: 'Erlang LS',
    language: 'Erlang',
    npmPackage: 'erlang-ls',
    description: 'Language server for Erlang development',
    homepage: 'https://github.com/erlang-ls/erlang_ls',
    icon: icon('erlang'),
  },
  {
    id: 'clojure',
    name: 'clojure-lsp',
    language: 'Clojure',
    npmPackage: 'clojure-lsp',
    description: 'Language server for Clojure with REPL integration',
    homepage: 'https://github.com/clojure-lsp/clojure-lsp',
    icon: icon('clojure'),
  },
  {
    id: 'haskell',
    name: 'Haskell Language Server',
    language: 'Haskell',
    npmPackage: 'haskell-language-server',
    description: 'Official Haskell language server',
    homepage: 'https://github.com/haskell/haskell-language-server',
    icon: icon('haskell'),
  },
  {
    id: 'ocaml',
    name: 'OCaml LSP',
    language: 'OCaml / ReasonML',
    npmPackage: 'ocaml-lsp-server',
    description: 'Language server for OCaml and ReasonML',
    homepage: 'https://github.com/ocaml/ocaml-lsp',
    icon: icon('ocaml'),
  },
  {
    id: 'elm',
    name: 'Elm Language Server',
    language: 'Elm',
    npmPackage: '@elm-tooling/elm-language-server',
    description: 'Language server for Elm programming',
    homepage: 'https://github.com/elm-tooling/elm-language-server',
    icon: icon('elm'),
  },
  {
    id: 'purescript',
    name: 'PureScript Language Server',
    language: 'PureScript',
    npmPackage: 'purescript-language-server',
    description: 'Language server for PureScript (Haskell-like for JS)',
    homepage: 'https://github.com/nwolverson/purescript-language-server',
    icon: icon('purescript'),
  },
  {
    id: 'rescript',
    name: 'ReScript Language Server',
    language: 'ReScript',
    npmPackage: '@rescript/language-server',
    description: 'Language server for ReScript (typed JS dialect)',
    homepage: 'https://github.com/rescript-lang/rescript-vscode',
    icon: icon('rescript'),
  },
  {
    id: 'gleam',
    name: 'Gleam Language Server',
    language: 'Gleam',
    npmPackage: 'gleam',
    description: 'Language server for Gleam (Elixir/BEAM typed language)',
    homepage: 'https://github.com/gleam-lang/gleam',
    icon: icon('gleam'),
  },
  {
    id: 'dart',
    name: 'Dart Analysis Server',
    language: 'Dart / Flutter',
    npmPackage: 'dart-language-server',
    description: 'Language server for Dart and Flutter',
    homepage: 'https://dart.dev/tools/dartanalyzer',
    icon: icon('dart'),
  },
  {
    id: 'swift',
    name: 'SourceKit-LSP',
    language: 'Swift',
    npmPackage: 'sourcekit-lsp',
    description: 'Official Swift language server from Apple',
    homepage: 'https://github.com/apple/sourcekit-lsp',
    icon: icon('swift'),
  },
  {
    id: 'groovy',
    name: 'Groovy Language Server',
    language: 'Groovy',
    npmPackage: 'groovy-language-server',
    description: 'Language server for Apache Groovy',
    homepage: 'https://github.com/GroovyLanguageServer/groovy-language-server',
    icon: icon('groovy'),
  },
  {
    id: 'julia',
    name: 'Julia Language Server',
    language: 'Julia',
    npmPackage: 'LanguageServer.jl',
    description: 'Language server for Julia scientific computing',
    homepage: 'https://github.com/julia-vscode/LanguageServer.jl',
    icon: icon('julia'),
  },
  {
    id: 'r',
    name: 'R Language Server',
    language: 'R',
    npmPackage: 'languageserver',
    description: 'Language server for R statistical computing',
    homepage: 'https://github.com/REditorSupport/languageserver',
    icon: icon('r'),
  },
  {
    id: 'perl',
    name: 'Perl Language Server',
    language: 'Perl',
    npmPackage: 'Perl-LanguageServer',
    description: 'Language server for Perl 5',
    homepage: 'https://github.com/richterger/Perl-LanguageServer',
    icon: icon('perl'),
  },
  {
    id: 'lua',
    name: 'Lua Language Server',
    language: 'Lua',
    npmPackage: 'lua-language-server',
    description: 'Fast Lua language server with type checking',
    homepage: 'https://github.com/LuaLS/lua-language-server',
    icon: icon('lua'),
  },

  // ═══════════════════════════════════════════════════════════════════════
  // SYSTEMS & EMBEDDED
  // ═══════════════════════════════════════════════════════════════════════
  {
    id: 'cpp',
    name: 'Clangd',
    language: 'C / C++',
    npmPackage: 'clangd',
    description: 'Fast and accurate C/C++ language server via LLVM',
    homepage: 'https://clangd.llvm.org/',
    icon: icon('cplusplus'),
  },
  {
    id: 'c',
    name: 'Clangd',
    language: 'C',
    npmPackage: 'clangd',
    description: 'C language support via Clangd',
    homepage: 'https://clangd.llvm.org/',
    icon: icon('c'),
  },
  {
    id: 'zig',
    name: 'ZLS',
    language: 'Zig',
    npmPackage: 'zls',
    description: 'Language server for Zig (fast C alternative)',
    homepage: 'https://github.com/zigtools/zls',
    icon: icon('zig'),
  },
  {
    id: 'nim',
    name: 'Nim Language Server',
    language: 'Nim',
    npmPackage: 'nimlsp',
    description: 'Language server for Nim programming',
    homepage: 'https://github.com/PMunch/nimlsp',
    icon: icon('nim'),
  },
  {
    id: 'vlang',
    name: 'V Language Server',
    language: 'V',
    npmPackage: 'v-analyzer',
    description: 'Language server for the V programming language',
    homepage: 'https://github.com/vlang/v-analyzer',
    icon: icon('vlang'),
  },
  {
    id: 'crystal',
    name: 'Crystalline',
    language: 'Crystal',
    npmPackage: 'crystalline',
    description: 'Language server for Crystal (Ruby-like, compiled)',
    homepage: 'https://github.com/elbywan/crystalline',
    icon: icon('crystal'),
  },
  {
    id: 'dlang',
    name: 'serve-d',
    language: 'D',
    npmPackage: 'serve-d',
    description: 'Language server for the D programming language',
    homepage: 'https://github.com/Pure-D/serve-d',
    icon: icon('d'),
  },
  {
    id: 'haxe',
    name: 'Haxe Language Server',
    language: 'Haxe',
    npmPackage: 'haxe-language-server',
    description: 'Language server for Haxe cross-platform toolkit',
    homepage: 'https://github.com/vshaxe/haxe-language-server',
    icon: icon('haxe'),
  },
  {
    id: 'vala',
    name: 'Vala Language Server',
    language: 'Vala',
    npmPackage: 'vala-language-server',
    description: 'Language server for Vala (GNOME language)',
    homepage: 'https://github.com/Prince781/vala-language-server',
    icon: icon('vala'),
  },
  {
    id: 'fortran',
    name: 'fortls',
    language: 'Fortran',
    npmPackage: 'fortls',
    description: 'Language server for modern Fortran',
    homepage: 'https://github.com/fortran-lang/fortls',
    icon: icon('fortran'),
  },
  {
    id: 'ada',
    name: 'Ada Language Server',
    language: 'Ada',
    npmPackage: 'ada_language_server',
    description: 'Language server for Ada/SPARK programming',
    homepage: 'https://github.com/AdaCore/ada_language_server',
    icon: icon('ada'),
  },
  {
    id: 'pascal',
    name: 'Pascal Language Server',
    language: 'Pascal / Delphi',
    npmPackage: 'pasls',
    description: 'Language server for Pascal (Free Pascal / Delphi)',
    homepage: 'https://github.com/genericptr/pascal-language-server',
    icon: icon('pascal'),
  },

  // ═══════════════════════════════════════════════════════════════════════
  // CONFIGURATION & DATA FORMATS
  // ═══════════════════════════════════════════════════════════════════════
  {
    id: 'json',
    name: 'JSON Language Server',
    language: 'JSON',
    npmPackage: 'vscode-langservers-extracted',
    description: 'Schema validation and auto-complete for JSON files',
    homepage: 'https://github.com/hrsh7th/vscode-langservers-extracted',
    icon: icon('json'),
  },
  {
    id: 'json5',
    name: 'JSON5 Language Server',
    language: 'JSON5',
    npmPackage: 'json5-language-server',
    description: 'Language server for JSON5 (relaxed JSON syntax)',
    homepage: 'https://github.com/microsoft/node-jsonc-parser',
    icon: icon('json'),
  },
  {
    id: 'jsonnet',
    name: 'Jsonnet Language Server',
    language: 'Jsonnet',
    npmPackage: 'jsonnet-language-server',
    description: 'Language server for Jsonnet data templating',
    homepage: 'https://github.com/grafana/jsonnet-language-server',
    icon: icon('json'),
  },
  {
    id: 'yaml',
    name: 'YAML Language Server',
    language: 'YAML',
    npmPackage: 'yaml-language-server',
    description: 'Schema-based validation for YAML configuration files',
    homepage: 'https://github.com/redhat-developer/yaml-language-server',
    icon: icon('yaml'),
  },
  {
    id: 'toml',
    name: 'TOML Language Server',
    language: 'TOML',
    npmPackage: 'taplo-lsp',
    description: 'Language server for TOML configuration files',
    homepage: 'https://github.com/tamasfe/taplo',
    icon: icon('toml'),
  },
  {
    id: 'xml',
    name: 'XML Language Server',
    language: 'XML',
    npmPackage: 'lemminx',
    description: 'XML language server with schema validation',
    homepage: 'https://github.com/eclipse/lemminx',
    icon: icon('xml'),
  },
  {
    id: 'csv',
    name: 'CSV Language Server',
    language: 'CSV / TSV',
    npmPackage: 'csv-language-server',
    description: 'Language server for CSV/TSV with column alignment',
    homepage: 'https://github.com/mechatroner/csv-language-server',
    icon: icon('csv'),
  },
  {
    id: 'dotenv',
    name: 'DotENV Language Server',
    language: '.env files',
    npmPackage: 'dotenv-language-server',
    description: 'Validation and auto-complete for .env files',
    homepage: 'https://github.com/nickheal/dotenv-language-server',
    icon: icon('dotenv'),
  },
  {
    id: 'ini',
    name: 'INI Language Server',
    language: 'INI / .editorconfig',
    npmPackage: 'ini-language-server',
    description: 'Language server for INI and .editorconfig files',
    homepage: 'https://github.com/ecmel/ini-language-server',
    icon: icon('ini'),
  },
  {
    id: 'properties',
    name: 'Properties Language Server',
    language: 'Java .properties',
    npmPackage: 'properties-language-server',
    description: 'Language server for Java properties files',
    homepage: 'https://github.com/steven-solomon/properties-language-server',
    icon: icon('java'),
  },
  {
    id: 'protobuf',
    name: 'Buf Language Server',
    language: 'Protocol Buffers',
    npmPackage: 'buf',
    description: 'Language server for Protobuf with linting and breaking change detection',
    homepage: 'https://github.com/bufbuild/buf',
    icon: icon('protobuf'),
  },
  {
    id: 'thrift',
    name: 'Thrift Language Server',
    language: 'Apache Thrift',
    npmPackage: 'thrift-ls',
    description: 'Language server for Apache Thrift IDL',
    homepage: 'https://github.com/joyme123/thrift-ls',
    icon: icon('thrift'),
  },
  {
    id: 'graphql',
    name: 'GraphQL Language Server',
    language: 'GraphQL',
    npmPackage: 'graphql-language-service-server',
    description: 'IntelliSense for GraphQL schemas and queries',
    homepage: 'https://github.com/graphql/graphiql',
    icon: iconPlain('graphql'),
  },
  {
    id: 'cue',
    name: 'CUE Language Server',
    language: 'CUE',
    npmPackage: 'cue-lsp',
    description: 'Language server for CUE configuration language',
    homepage: 'https://github.com/cue-lang/cue',
    icon: icon('cue'),
  },
  {
    id: 'hcl',
    name: 'HCL Language Server',
    language: 'HCL',
    npmPackage: 'hcl-langserver',
    description: 'Language server for HashiCorp Configuration Language',
    homepage: 'https://github.com/hashicorp/hcl-langserver',
    icon: icon('hcl'),
  },
  {
    id: 'edn',
    name: 'EDN Language Server',
    language: 'EDN',
    npmPackage: 'edn-language-server',
    description: 'Language server for EDN (Extensible Data Notation)',
    homepage: 'https://github.com/freebroccolo/edn-language-server',
    icon: icon('clojure'),
  },

  // ═══════════════════════════════════════════════════════════════════════
  // BUILD & TOOLING
  // ═══════════════════════════════════════════════════════════════════════
  {
    id: 'cmake',
    name: 'CMake Language Server',
    language: 'CMake',
    npmPackage: 'cmake-language-server',
    description: 'Language server for CMake build scripts',
    homepage: 'https://github.com/regen100/cmake-language-server',
    icon: icon('cmake'),
  },
  {
    id: 'makefile',
    name: 'Makefile Language Server',
    language: 'Makefile',
    npmPackage: 'makefile-language-server',
    description: 'Language server for GNU Makefiles',
    homepage: 'https://github.com/kiennq/makefile-language-server',
    icon: icon('makefile'),
  },
  {
    id: 'bazel',
    name: 'Bazel Language Server',
    language: 'Bazel / Starlark',
    npmPackage: 'bazel-lsp',
    description: 'Language server for Bazel BUILD and .bzl files',
    homepage: 'https://github.com/sourcegraph/bazel-lsp',
    icon: icon('bazel'),
  },
  {
    id: 'gradle',
    name: 'Gradle Language Server',
    language: 'Gradle (Groovy/Kotlin DSL)',
    npmPackage: 'gradle-language-server',
    description: 'Language server for Gradle build scripts',
    homepage: 'https://github.com/microsoft/vscode-gradle',
    icon: icon('gradle'),
  },
  {
    id: 'nix',
    name: 'nil',
    language: 'Nix',
    npmPackage: 'nil',
    description: 'Fast language server for Nix expressions',
    homepage: 'https://github.com/oxalica/nil',
    icon: icon('nix'),
  },
  {
    id: 'meson',
    name: 'Meson Language Server',
    language: 'Meson',
    npmPackage: 'mesonlsp',
    description: 'Language server for Meson build system',
    homepage: 'https://github.com/mesonbuild/meson',
    icon: icon('meson'),
  },
  {
    id: 'justfile',
    name: 'Just Language Server',
    language: 'Justfile',
    npmPackage: 'just-lsp',
    description: 'Language server for Just command runner files',
    homepage: 'https://github.com/casey/just',
    icon: icon('just'),
  },

  // ═══════════════════════════════════════════════════════════════════════
  // MARKUP & DOCUMENTATION
  // ═══════════════════════════════════════════════════════════════════════
  {
    id: 'markdown',
    name: 'Marksman',
    language: 'Markdown',
    npmPackage: 'marksman',
    description: 'Markdown LSP with link completion and diagnostics',
    homepage: 'https://github.com/artempyanykh/marksman',
    icon: icon('markdown'),
  },
  {
    id: 'latex',
    name: 'TexLab',
    language: 'LaTeX',
    npmPackage: 'texlab',
    description: 'Language server for LaTeX documents',
    homepage: 'https://github.com/latex-lsp/texlab',
    icon: icon('latex'),
  },
  {
    id: 'asciidoc',
    name: 'AsciiDoc Language Server',
    language: 'AsciiDoc',
    npmPackage: 'asciidoc-ls',
    description: 'Language server for AsciiDoc documentation',
    homepage: 'https://github.com/asciidoctor/asciidoctor-lsp',
    icon: icon('asciidoc'),
  },
  {
    id: 'restructuredtext',
    name: 'esbonio',
    language: 'reStructuredText',
    npmPackage: 'esbonio',
    description: 'Language server for reStructuredText / Sphinx docs',
    homepage: 'https://github.com/swyddfa/esbonio',
    icon: icon('restructuredtext'),
  },
  {
    id: 'orgmode',
    name: 'Org Mode Language Server',
    language: 'Org Mode',
    npmPackage: 'org-babel-language-server',
    description: 'Language server for Emacs Org-mode files',
    homepage: 'https://github.com/vapourismo/org-babel-language-server',
    icon: icon('org'),
  },
  {
    id: 'typst',
    name: 'Typst LSP',
    language: 'Typst',
    npmPackage: 'typst-lsp',
    description: 'Language server for Typst (modern LaTeX alternative)',
    homepage: 'https://github.com/nvarner/typst-lsp',
    icon: icon('typst'),
  },

  // ═══════════════════════════════════════════════════════════════════════
  // DATABASE & QUERY LANGUAGES
  // ═══════════════════════════════════════════════════════════════════════
  {
    id: 'sql',
    name: 'SQL Language Server',
    language: 'SQL',
    npmPackage: 'sql-language-server',
    description: 'Language server for SQL with dialect support',
    homepage: 'https://github.com/joe-re/sql-language-server',
    icon: icon('postgresql'),
  },
  {
    id: 'prisma',
    name: 'Prisma Language Server',
    language: 'Prisma Schema',
    npmPackage: '@prisma/language-server',
    description: 'IntelliSense for Prisma ORM schemas',
    homepage: 'https://github.com/prisma/language-tools',
    icon: icon('prisma'),
  },
  {
    id: 'duckdb',
    name: 'DuckDB Language Server',
    language: 'DuckDB SQL',
    npmPackage: 'duckdb-lsp',
    description: 'Language server for DuckDB SQL dialect',
    homepage: 'https://github.com/duckdb/duckdb',
    icon: icon('duckdb'),
  },
  {
    id: 'plsql',
    name: 'PL/SQL Language Server',
    language: 'PL/SQL',
    npmPackage: 'plsql-language-server',
    description: 'Language server for Oracle PL/SQL',
    homepage: 'https://github.com/oracle/plsql-language-server',
    icon: icon('oracle'),
  },

  // ═══════════════════════════════════════════════════════════════════════
  // DEVOPS & INFRASTRUCTURE
  // ═══════════════════════════════════════════════════════════════════════
  {
    id: 'dockerfile',
    name: 'Dockerfile Language Server',
    language: 'Dockerfile',
    npmPackage: 'dockerfile-language-server-nodejs',
    description: 'IntelliSense for Dockerfiles',
    homepage: 'https://github.com/rcjsuen/dockerfile-language-server-nodejs',
    icon: icon('docker'),
  },
  {
    id: 'dockercompose',
    name: 'Docker Compose Language Service',
    language: 'Docker Compose',
    npmPackage: 'docker-compose-language-service',
    description: 'IntelliSense for docker-compose.yml files',
    homepage: 'https://github.com/microsoft/compose-language-service',
    icon: icon('docker'),
  },
  {
    id: 'terraform',
    name: 'Terraform LS',
    language: 'Terraform / HCL',
    npmPackage: 'terraform-ls',
    description: 'Language server for Terraform and HCL',
    homepage: 'https://github.com/hashicorp/terraform-ls',
    icon: icon('terraform'),
  },
  {
    id: 'ansible',
    name: 'Ansible Language Server',
    language: 'Ansible',
    npmPackage: 'ansible-language-server',
    description: 'Language server for Ansible playbooks',
    homepage: 'https://github.com/ansible/ansible-language-server',
    icon: icon('ansible'),
  },
  {
    id: 'kubernetes',
    name: 'Kubernetes Language Server',
    language: 'Kubernetes YAML',
    npmPackage: 'kubernetes-language-server',
    description: 'IntelliSense for Kubernetes manifests and Helm charts',
    homepage: 'https://github.com/redhat-developer/yaml-language-server',
    icon: icon('kubernetes'),
  },
  {
    id: 'helm',
    name: 'Helm Language Server',
    language: 'Helm Charts',
    npmPackage: 'helm-ls',
    description: 'Language server for Helm templates',
    homepage: 'https://github.com/mrjosh/helm-ls',
    icon: icon('helm'),
  },
  {
    id: 'kustomize',
    name: 'Kustomize Language Server',
    language: 'Kustomize',
    npmPackage: 'kustomize-language-server',
    description: 'Language server for Kustomize overlay files',
    homepage: 'https://github.com/sigs.k8s.io/kustomize',
    icon: icon('kustomize'),
  },
  {
    id: 'pulumi',
    name: 'Pulumi Language Server',
    language: 'Pulumi',
    npmPackage: '@pulumi/language-server',
    description: 'Language server for Pulumi IaC',
    homepage: 'https://github.com/pulumi/pulumi',
    icon: icon('pulumi'),
  },
  {
    id: 'bicep',
    name: 'Bicep Language Server',
    language: 'Azure Bicep',
    npmPackage: '@azure/bicep-language-server',
    description: 'Language server for Azure Bicep templates',
    homepage: 'https://github.com/Azure/bicep',
    icon: icon('azure'),
  },
  {
    id: 'cloudformation',
    name: 'CloudFormation Language Server',
    language: 'AWS CloudFormation',
    npmPackage: 'cloudformation-lsp',
    description: 'Language server for AWS CloudFormation templates',
    homepage: 'https://github.com/aws-cloudformation/cfn-lint',
    icon: icon('amazonwebservices'),
  },
  {
    id: 'serverless',
    name: 'Serverless Framework Language Server',
    language: 'serverless.yml',
    npmPackage: 'serverless-language-server',
    description: 'IntelliSense for Serverless Framework config',
    homepage: 'https://github.com/serverless/serverless',
    icon: icon('serverless'),
  },
  {
    id: 'nginx',
    name: 'NGINX Language Server',
    language: 'NGINX Config',
    npmPackage: 'nginx-language-server',
    description: 'Language server for NGINX configuration files',
    homepage: 'https://github.com/nginx/nginx-language-server',
    icon: icon('nginx'),
  },

  // ═══════════════════════════════════════════════════════════════════════
  // SCRIPTING & SHELL
  // ═══════════════════════════════════════════════════════════════════════
  {
    id: 'bash',
    name: 'Bash Language Server',
    language: 'Bash / Shell',
    npmPackage: 'bash-language-server',
    description: 'Linting, auto-complete for shell scripts',
    homepage: 'https://github.com/bash-lsp/bash-language-server',
    icon: icon('bash'),
  },
  {
    id: 'powershell',
    name: 'PowerShell Editor Services',
    language: 'PowerShell',
    npmPackage: 'powershell-editor-services',
    description: 'Language server for PowerShell scripts',
    homepage: 'https://github.com/PowerShell/PowerShellEditorServices',
    icon: icon('powershell'),
  },
  {
    id: 'vimscript',
    name: 'Vim Language Server',
    language: 'VimScript',
    npmPackage: 'vim-language-server',
    description: 'Language server for Vim9script and vimrc files',
    homepage: 'https://github.com/iamcco/vim-language-server',
    icon: icon('vim'),
  },

  // ═══════════════════════════════════════════════════════════════════════
  // HARDWARE DESCRIPTION (HDL)
  // ═══════════════════════════════════════════════════════════════════════
  {
    id: 'vhdl',
    name: 'VHDL Language Server',
    language: 'VHDL',
    npmPackage: 'vhdl-ls',
    description: 'Language server for VHDL hardware description',
    homepage: 'https://github.com/VHDL-LS/rust_hdl_ls',
    icon: icon('vhdl'),
  },
  {
    id: 'verilog',
    name: 'Verilog Language Server',
    language: 'Verilog / SystemVerilog',
    npmPackage: 'svlangserver',
    description: 'Language server for Verilog and SystemVerilog HDL',
    homepage: 'https://github.com/imc-trading/svlangserver',
    icon: icon('verilog'),
  },

  // ═══════════════════════════════════════════════════════════════════════
  // SHADER & GRAPHICS
  // ═══════════════════════════════════════════════════════════════════════
  {
    id: 'glsl',
    name: 'GLSL Language Server',
    language: 'GLSL',
    npmPackage: 'glsl_analyzer',
    description: 'Language server for OpenGL Shading Language',
    homepage: 'https://github.com/nolanderc/glsl_analyzer',
    icon: icon('opengl'),
  },
  {
    id: 'hlsl',
    name: 'HLSL Language Server',
    language: 'HLSL',
    npmPackage: 'hlsl-language-server',
    description: 'Language server for High-Level Shading Language (DirectX)',
    homepage: 'https://github.com/microsoft/hlsl-language-server',
    icon: icon('directx'),
  },
  {
    id: 'wgsl',
    name: 'WGSL Language Server',
    language: 'WGSL',
    npmPackage: 'wgsl-analyzer',
    description: 'Language server for WebGPU Shading Language',
    homepage: 'https://github.com/wgsl-analyzer/wgsl-analyzer',
    icon: icon('webgpu'),
  },

  // ═══════════════════════════════════════════════════════════════════════
  // GAME DEVELOPMENT
  // ═══════════════════════════════════════════════════════════════════════
  {
    id: 'gdscript',
    name: 'Godot Language Server',
    language: 'GDScript',
    npmPackage: 'godot-language-server',
    description: 'Language server for Godot Engine GDScript',
    homepage: 'https://github.com/godotengine/godot',
    icon: icon('godot'),
  },
  {
    id: 'csharp_unity',
    name: 'OmniSharp (Unity)',
    language: 'C# / Unity',
    npmPackage: 'omnisharp-roslyn',
    description: 'C# language server optimized for Unity projects',
    homepage: 'https://github.com/OmniSharp/omnisharp-roslyn',
    icon: icon('unity'),
  },

  // ═══════════════════════════════════════════════════════════════════════
  // SCIENTIFIC & NUMERICAL
  // ═══════════════════════════════════════════════════════════════════════
  {
    id: 'matlab',
    name: 'MATLAB Language Server',
    language: 'MATLAB',
    npmPackage: 'matlab-language-server',
    description: 'Language server for MATLAB',
    homepage: 'https://github.com/mathworks/MATLAB-language-server',
    icon: icon('matlab'),
  },
  {
    id: 'stata',
    name: 'Stata Language Server',
    language: 'Stata',
    npmPackage: 'stata-lsp',
    description: 'Language server for Stata statistical software',
    homepage: 'https://github.com/haghish/stata-lsp',
    icon: icon('stata'),
  },

  // ═══════════════════════════════════════════════════════════════════════
  // LEGACY & ENTERPRISE
  // ═══════════════════════════════════════════════════════════════════════
  {
    id: 'cobol',
    name: 'COBOL Language Server',
    language: 'COBOL',
    npmPackage: 'cobol-language-support',
    description: 'Language server for COBOL mainframe programming',
    homepage: 'https://github.com/eclipse/che-che4z-lsp-for-cobol',
    icon: icon('cobol'),
  },
  {
    id: 'abap',
    name: 'ABAP Language Server',
    language: 'SAP ABAP',
    npmPackage: 'abapls',
    description: 'Language server for SAP ABAP',
    homepage: 'https://github.com/abaplint/abapls',
    icon: icon('abap'),
  },

  // ═══════════════════════════════════════════════════════════════════════
  // DOMAIN-SPECIFIC
  // ═══════════════════════════════════════════════════════════════════════
  {
    id: 'regex',
    name: 'Regex Language Server',
    language: 'Regular Expressions',
    npmPackage: 'regex-lsp',
    description: 'Language server for regular expressions with explainer',
    homepage: 'https://github.com/jdpopkin/regex-lsp',
    icon: icon('regex'),
  },
  {
    id: 'gcode',
    name: 'G-Code Language Server',
    language: 'G-Code',
    npmPackage: 'gcode-language-server',
    description: 'Language server for G-Code (CNC/3D printing)',
    homepage: 'https://github.com/robterrace/gcode-language-server',
    icon: icon('gcode'),
  },
  {
    id: 'openscad',
    name: 'OpenSCAD Language Server',
    language: 'OpenSCAD',
    npmPackage: 'openscad-lsp',
    description: 'Language server for OpenSCAD 3D modeling',
    homepage: 'https://github.com/Leathong/openscad-lsp',
    icon: icon('openscad'),
  },
  {
    id: 'ttcn3',
    name: 'TTCN-3 Language Server',
    language: 'TTCN-3',
    npmPackage: 'ttcn3-lsp',
    description: 'Language server for TTCN-3 testing language',
    homepage: 'https://github.com/nokia/ttcn3-lsp',
    icon: icon('ttcn'),
  },
];
